const STATS = [
  { name: "Max Health", icon: "icons/max_health.png", temp: false, category: "survival",
    desc: "+10% max HP per rank. Base is 50 HP. You still need to heal to fill the new cap." },
  { name: "Recovery", icon: "icons/recovery.webp", temp: false, category: "survival",
    desc: "Heals 1 HP per rank after each encounter. Up to +3 HP passively per room." },
  { name: "Armor", icon: "icons/armor.webp", temp: false, category: "survival",
    desc: "Grants starting Armor each turn. +2 per rank. Absorbs damage before HP is touched." },
  { name: "Revival", icon: "icons/revival.png", temp: false, category: "survival",
    desc: "Revive once on death per rank. Max 1 from Power Ups. Safety net for tough fights." },
  { name: "Might", icon: "icons/might.webp", temp: true, category: "offense",
    desc: "+25% damage to all attack cards per rank. Universal — scales your whole deck." },
  { name: "Area", icon: "icons/area.png", temp: true, category: "offense",
    desc: "+10% splash radius per rank. Hits enemies beyond the primary target." },
  { name: "Amount", icon: "icons/amount.png", temp: true, category: "offense",
    desc: "+1 projectile per weapon card per rank. Multiplies output — strongest scaling stat." },
  { name: "Duration", icon: "icons/duration.png", temp: true, category: "offense",
    desc: "Crawlers stay active +1 trigger longer per rank. More triggers = more damage." },
  { name: "Hand", icon: "icons/hand.png", temp: true, category: "deck",
    desc: "Draw +1 card per turn per rank. Base is 3. More options every turn." },
  { name: "Mana", icon: "icons/mana.webp", temp: false, category: "deck",
    desc: "+1 starting Mana per rank. Base is 2. Lets you play more cards per turn." },
  { name: "Magnet", icon: "icons/magnet.png", temp: false, category: "deck",
    desc: "Boosts draw card effects by +1. E.g. Attractorb draws 2 cards instead of 1." },
  { name: "Luck", icon: "icons/luck.png", temp: false, category: "meta",
    desc: "+25% per rank. Better crit chance, drop rate, and drop quality." },
  { name: "Growth", icon: "icons/growth.png", temp: false, category: "meta",
    desc: "+20% XP per rank. Level up faster, get more cards and gems sooner." },
  { name: "Greed", icon: "icons/greed.webp", temp: false, category: "meta",
    desc: "+25% Gold per rank. Snowballs hard — more gold = faster Power Ups." },
  { name: "Reroll", icon: "icons/reroll.png", temp: false, category: "control",
    desc: "+2 reroll options per rank. Swap bad level-up or treasure rewards." },
  { name: "Skip", icon: "icons/skip.png", temp: false, category: "control",
    desc: "+2 skips per rank. Pass on rewards for bonus XP instead." },
  { name: "Banish", icon: "icons/banish.png", temp: false, category: "control",
    desc: "+2 banishes per rank. Permanently remove cards from appearing." },
  { name: "Curse", icon: "icons/curse.png", temp: false, category: "risk",
    desc: "Enemies +20% stronger per rank — but you earn more XP and Gold. Risk/reward." },
];

const CATEGORIES = {
  all:      { label: "All",      color: "#c8a050" },
  survival: { label: "Survival", color: "#e05050" },
  offense:  { label: "Offense",  color: "#e08030" },
  deck:     { label: "Deck",     color: "#5090e0" },
  meta:     { label: "Meta",     color: "#50c080" },
  control:  { label: "Control",  color: "#a060e0" },
  risk:     { label: "Risk",     color: "#c04060" },
};

const EVOLUTIONS = [
  { base: "Whip", item: "Hollow Heart", alt: "Forever Heart", result: "Bloody Tear", type: "evo",
    desc: "Deals AoE damage and heals on crit hit. One of the easiest strong evolutions — solid arc damage with sustain." },
  { base: "Knife", item: "Bracer", alt: null, result: "Thousand Edge", type: "evo",
    desc: "Deals damage to all enemies in the front row. Strong early damage spike, fits combo decks." },
  { base: "Magic Wand", item: "Empty Tome", alt: "Light Tome, Weighty Tome, Ancient Tome", result: "Holy Wand", type: "evo",
    desc: "Shoots projectiles targeting enemies bound to attack. Scales heavily with Mana Chain multipliers." },
  { base: "Axe", item: "Candella", alt: "Candle, Candelabrador", result: "Death Spiral", type: "evo",
    desc: "Creates a permanent rotating shield that damages enemies continuously." },
  { base: "King Bible", item: "Spellbinder", alt: null, result: "Unholy Vespers", type: "evo",
    desc: "Deals AoE damage and knocks back enemies one row. One of the best defensive evolutions." },
  { base: "Fire Wand", item: "Spinach", alt: "Sprig o' Spinach", result: "Hellfire", type: "evo",
    desc: "Shoots powerful fireballs that also knock back enemies." },
  { base: "Garlic", item: "Pummarola", alt: "Pummadora", result: "Soul Eater", type: "evo",
    desc: "Improves Garlic's area damage and Disarm effect." },
  { base: "Santa Water", item: "Attractorb", alt: null, result: "La Borra", type: "evo",
    desc: "~360 damage and burns enemies after each turn. Scales well with Mana Chain." },
  { base: "Runetracer", item: "Armor", alt: "Golden Armor, Rainbow Armor, Hero's Armor", result: "NO FUTURE", type: "evo",
    desc: "Creates explosive projectiles dealing massive burst damage on contact. Best late-run evolution." },
  { base: "Lightning Ring", item: "Duplicator", alt: null, result: "Thunder Loop", type: "evo",
    desc: "Deals 150 damage. Attacks again at end of turn." },
  { base: "Cross", item: "Clover", alt: null, result: "Heaven Sword", type: "evo",
    desc: "Deals 100 damage with a chance of dealing crit damage." },
  { base: "Song of Mana", item: "Skull O'Maniac", alt: null, result: "Mannajja", type: "evo",
    desc: "Powerful AoE evolution combining mana song effects with skull damage scaling." },
  { base: "Pentagram", item: "Crown", alt: null, result: "Gorgeous Moon", type: "evo",
    desc: "Devastating board-wipe evolution. Pentagram's clearing power amplified by Crown's XP gain." },
  { base: "Gatti Amari", item: "Stone Mask", alt: null, result: "Vicious Hunger", type: "evo",
    desc: "Deals 100 base damage. May turn enemies into coins — strong synergy with Greed." },
  { base: "Shadow Pinion", item: "Wings", alt: null, result: "Valkyrie Turner", type: "evo",
    desc: "Shadow Pinion fused with Wings for amplified mobility-based attack pattern." },
  { base: "Peachone", item: "Ebony Wings", alt: null, result: "Vandalier", type: "evo",
    desc: "Deals 500 damage with knockback chance. Big Bird: disperses all active birds for increased damage." },
  { base: "Phiera Der Tuphello + Eight the Sparrow", item: "Tirajisú", alt: "UNION: all 3 cards consumed", result: "Phieraggi", type: "union",
    desc: "Deals 350 damage. Combines firepower of both base guns into one evolved weapon." },
];
