const STATS = [
  { name: "Max Health", icon: "./icons/max_health.png", temp: false, category: "survival",
    desc: "+10% max HP per rank. Base is 50 HP. You still need to heal to fill the new cap." },
  { name: "Recovery", icon: "./icons/recovery.png", temp: false, category: "survival",
    desc: "Heals 1 HP per rank after each encounter. Up to +3 HP passively per room." },
  { name: "Armor", icon: "./icons/armor.png", temp: false, category: "survival",
    desc: "Grants starting Armor each turn. +2 per rank. Absorbs damage before HP is touched." },
  { name: "Revival", icon: "./icons/revival.png", temp: false, category: "survival",
    desc: "Revive once on death per rank. Max 1 from Power Ups. Safety net for tough fights." },
  { name: "Might", icon: "./icons/might.png", temp: true, category: "offense",
    desc: "+25% damage to all attack cards per rank. Universal — scales your whole deck." },
  { name: "Area", icon: "./icons/area.png", temp: true, category: "offense",
    desc: "+10% splash radius per rank. Hits enemies beyond the primary target." },
  { name: "Amount", icon: "./icons/amount.png", temp: true, category: "offense",
    desc: "+1 projectile per weapon card per rank. Multiplies output — strongest scaling stat." },
  { name: "Duration", icon: "./icons/duration.png", temp: true, category: "offense",
    desc: "Crawlers stay active +1 trigger longer per rank. More triggers = more damage." },
  { name: "Hand", icon: "./icons/hand.png", temp: true, category: "deck",
    desc: "Draw +1 card per turn per rank. Base is 3. More options every turn." },
  { name: "Mana", icon: "./icons/mana.png", temp: false, category: "deck",
    desc: "+1 starting Mana per rank. Base is 2. Lets you play more cards per turn." },
  { name: "Magnet", icon: "./icons/magnet.png", temp: false, category: "deck",
    desc: "Boosts draw card effects by +1. E.g. Attractorb draws 2 cards instead of 1." },
  { name: "Luck", icon: "./icons/luck.png", temp: false, category: "meta",
    desc: "+25% per rank. Better crit chance, drop rate, and drop quality." },
  { name: "Growth", icon: "./icons/growth.png", temp: false, category: "meta",
    desc: "+20% XP per rank. Level up faster, get more cards and gems sooner." },
  { name: "Greed", icon: "./icons/greed.png", temp: false, category: "meta",
    desc: "+25% Gold per rank. Snowballs hard — more gold = faster Power Ups." },
  { name: "Reroll", icon: "./icons/reroll.png", temp: false, category: "control",
    desc: "+2 reroll options per rank. Swap bad level-up or treasure rewards." },
  { name: "Skip", icon: "./icons/skip.png", temp: false, category: "control",
    desc: "+2 skips per rank. Pass on rewards for bonus XP instead." },
  { name: "Banish", icon: "./icons/banish.png", temp: false, category: "control",
    desc: "+2 banishes per rank. Permanently remove cards from appearing." },
  { name: "Curse", icon: "./icons/curse.png", temp: false, category: "risk",
    desc: "Enemies +20% stronger per rank — but you earn more XP and Gold. Risk/reward." },
];

const CATEGORIES = {
  all:      { label: "All",      color: "#c8a050" },
  survival: { label: "Survival", color: "#e05050" },
  offense:  { label: "Offense",  color: "#e08030" },
  deck:     { label: "Deck",     color: "#5090e0" },
  meta:     { label: "Meta",     color: "#50c080" },
  control:  { label: "Control",  color: "#a060e0" },
  risk:     { label: "Risk",     color: "#c04060" },
};

const EVOLUTIONS = [
  { base: "Whip",      base_icon: "Whip",
    item: "Hollow Heart", item_icon: "Hollow_Heart",
    result: "Bloody Tear", result_icon: "Bloody_Tear",
    extra_icon: null, alt: "Forever Heart", type: "evo",
    desc: "Deals AoE damage and heals on crit hit. Solid arc damage with sustain." },

  { base: "Knife",     base_icon: "Knife",
    item: "Bracer",    item_icon: "Bracer",
    result: "Thousand Edge", result_icon: "Thousand_Edge",
    extra_icon: null, alt: null, type: "evo",
    desc: "Deals damage to all enemies in the front row. Strong early damage spike." },

  { base: "Magic Wand", base_icon: "Magic_Wand",
    item: "Empty Tome", item_icon: "Empty_Tome",
    result: "Holy Wand", result_icon: "Holy_Wand",
    extra_icon: null, alt: "Light Tome, Weighty Tome, Ancient Tome", type: "evo",
    desc: "Shoots projectiles targeting enemies bound to attack. Scales with Mana Chain." },

  { base: "Axe",       base_icon: "Axe",
    item: "Candella",  item_icon: "Candella",
    result: "Death Spiral", result_icon: "Death_Spiral",
    extra_icon: null, alt: "Candle, Candelabrador", type: "evo",
    desc: "Creates a permanent rotating shield that damages enemies continuously." },

  { base: "King Bible", base_icon: "King_Bible",
    item: "Spellbinder", item_icon: "Spellbinder",
    result: "Unholy Vespers", result_icon: "Unholy_Vespers",
    extra_icon: null, alt: null, type: "evo",
    desc: "Deals AoE damage and knocks back enemies one row. One of the best defensive evolutions." },

  { base: "Fire Wand", base_icon: "Fire_Wand",
    item: "Spinach",   item_icon: "Spinach",
    result: "Hellfire", result_icon: "Hellfire",
    extra_icon: null, alt: "Sprig o' Spinach", type: "evo",
    desc: "Shoots powerful fireballs that also knock back enemies." },

  { base: "Garlic",    base_icon: "Garlic",
    item: "Pummarola", item_icon: "Pummarola",
    result: "Soul Eater", result_icon: "Soul_Eater",
    extra_icon: null, alt: "Pummadora", type: "evo",
    desc: "Improves Garlic's area damage and Disarm effect." },

  { base: "Santa Water", base_icon: "Santa_Water",
    item: "Attractorb", item_icon: "Attractorb",
    result: "La Borra", result_icon: "La_Borra",
    extra_icon: null, alt: null, type: "evo",
    desc: "~360 damage and burns enemies after each turn. Scales well with Mana Chain." },

  { base: "Runetracer", base_icon: "Runetracer",
    item: "Armor",     item_icon: "Armor",
    result: "NO FUTURE", result_icon: "No_Future",
    extra_icon: null, alt: "Golden/Rainbow/Hero's Armor", type: "evo",
    desc: "Explosive projectiles dealing massive burst damage on contact. Best late-run evolution." },

  { base: "Lightning Ring", base_icon: "Lightning_Ring",
    item: "Duplicator", item_icon: "Duplicator",
    result: "Thunder Loop", result_icon: "Thunder_Loop",
    extra_icon: null, alt: null, type: "evo",
    desc: "Deals 150 damage. Attacks again at end of turn." },

  { base: "Cross",     base_icon: "Cross",
    item: "Clover",    item_icon: "Clover",
    result: "Heaven Sword", result_icon: "Heaven_Sword",
    extra_icon: null, alt: null, type: "evo",
    desc: "Deals 100 damage with a chance of crit damage." },

  { base: "Song of Mana", base_icon: "Song_Of_Mana",
    item: "Skull O'Maniac", item_icon: "Skull_O_Maniac",
    result: "Mannajja", result_icon: "Mannajja",
    extra_icon: null, alt: null, type: "evo",
    desc: "Powerful AoE evolution combining mana song effects with skull damage scaling." },

  { base: "Pentagram", base_icon: "Pentagram",
    item: "Crown",     item_icon: "Crown",
    result: "Gorgeous Moon", result_icon: "Gorgeous_Moon",
    extra_icon: null, alt: null, type: "evo",
    desc: "Devastating board-wipe evolution. Pentagram's clearing power amplified by Crown's XP gain." },

  { base: "Gatti Amari", base_icon: "Gatti_Amari",
    item: "Stone Mask", item_icon: "Stone_Mask",
    result: "Vicious Hunger", result_icon: "Vicious_Hunger",
    extra_icon: null, alt: null, type: "evo",
    desc: "Deals 100 base damage. May turn enemies into coins — strong synergy with Greed." },

  { base: "Shadow Pinion", base_icon: "Shadow_Pinion",
    item: "Wings",     item_icon: "Wings",
    result: "Valkyrie Turner", result_icon: "Valkyrie_Turner",
    extra_icon: null, alt: null, type: "evo",
    desc: "Shadow Pinion fused with Wings for amplified mobility-based attack pattern." },

  { base: "Peachone",  base_icon: "Peachone",
    item: "Ebony Wings", item_icon: "Ebony_Wings",
    result: "Vandalier", result_icon: "Vandalier",
    extra_icon: null, alt: null, type: "evo",
    desc: "Deals 500 damage with knockback chance. Big Bird: disperses all active birds for increased damage." },

  { base: "Phiera Der Tuphello + Eight the Sparrow", base_icon: "Phiera_Der_Tuphello",
    item: "Tirajisu",  item_icon: "Tirajisu",
    result: "Phieraggi", result_icon: "Phieraggi",
    extra_icon: "Eight_The_Sparrow", alt: "UNION: all 3 cards consumed", type: "union",
    desc: "Deals 350 damage. Combines firepower of both base guns into one evolved weapon." },
];
