const STATS = [
  { name: "Max Health", icon: "icons/max_health.png", temp: false, category: "survival",
    desc: "+10% max HP per rank. Base is 50 HP. You still need to heal to fill the new cap." },
  { name: "Recovery", icon: "icons/recovery.webp", temp: false, category: "survival",
    desc: "Heals 1 HP per rank after each encounter. Up to +3 HP passively per room." },
  { name: "Armor", icon: "icons/armor.webp", temp: false, category: "survival",
    desc: "Grants starting Armor each turn. +2 per rank. Absorbs damage before HP is touched." },
  { name: "Revival", icon: "icons/revival.png", temp: false, category: "survival",
    desc: "Revive once on death per rank. Max 1 from Power Ups. Safety net for tough fights." },
  { name: "Might", icon: "icons/might.webp", temp: true, category: "offense",
    desc: "+25% damage to all attack cards per rank. Universal — scales your whole deck." },
  { name: "Area", icon: "icons/area.png", temp: true, category: "offense",
    desc: "+10% splash radius per rank. Hits enemies beyond the primary target." },
  { name: "Amount", icon: "icons/amount.png", temp: true, category: "offense",
    desc: "+1 projectile per weapon card per rank. Multiplies output — strongest scaling stat." },
  { name: "Duration", icon: "icons/duration.png", temp: true, category: "offense",
    desc: "Crawlers stay active +1 trigger longer per rank. More triggers = more damage." },
  { name: "Hand", icon: "icons/hand.png", temp: true, category: "deck",
    desc: "Draw +1 card per turn per rank. Base is 3. More options every turn." },
  { name: "Mana", icon: "icons/mana.webp", temp: false, category: "deck",
    desc: "+1 starting Mana per rank. Base is 2. Lets you play more cards per turn." },
  { name: "Magnet", icon: "icons/magnet.png", temp: false, category: "deck",
    desc: "Boosts draw card effects by +1. E.g. Attractorb draws 2 cards instead of 1." },
  { name: "Luck", icon: "icons/luck.png", temp: false, category: "meta",
    desc: "+25% per rank. Better crit chance, drop rate, and drop quality." },
  { name: "Growth", icon: "icons/growth.png", temp: false, category: "meta",
    desc: "+20% XP per rank. Level up faster, get more cards and gems sooner." },
  { name: "Greed", icon: "icons/greed.webp", temp: false, category: "meta",
    desc: "+25% Gold per rank. Snowballs hard — more gold = faster Power Ups." },
  { name: "Reroll", icon: "icons/reroll.png", temp: false, category: "control",
    desc: "+2 reroll options per rank. Swap bad level-up or treasure rewards." },
  { name: "Skip", icon: "icons/skip.png", temp: false, category: "control",
    desc: "+2 skips per rank. Pass on rewards for bonus XP instead." },
  { name: "Banish", icon: "icons/banish.png", temp: false, category: "control",
    desc: "+2 banishes per rank. Permanently remove cards from appearing." },
  { name: "Curse", icon: "icons/curse.png", temp: false, category: "risk",
    desc: "Enemies +20% stronger per rank — but you earn more XP and Gold. Risk/reward." },
];

const CATEGORIES = {
  all:      { label: "All",      color: "#c8a050" },
  survival: { label: "Survival", color: "#e05050" },
  offense:  { label: "Offense",  color: "#e08030" },
  deck:     { label: "Deck",     color: "#5090e0" },
  meta:     { label: "Meta",     color: "#50c080" },
  control:  { label: "Control",  color: "#a060e0" },
  risk:     { label: "Risk",     color: "#c04060" },
};
